from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

def generate_pdf(filename="output.pdf"):
    # Create the PDF document
    pdf = SimpleDocTemplate(filename, pagesize=A4)

    styles = getSampleStyleSheet()
    content = []

    # Title
    title = Paragraph("<b>PDF Report Generated Using Python</b>", styles["Title"])
    content.append(title)
    content.append(Spacer(1, 20))

    # Body text
    text = """
    This is a sample PDF generated using the <b>reportlab</b> library.
    You can use this for:
    - College assignments
    - Data science reports
    - Project documentation
    - ML model summaries
    """

    para = Paragraph(text, styles["Normal"])
    content.append(para)
    content.append(Spacer(1, 20))

    # Footer
    footer = Paragraph("Generated by Python 🚀", styles["Italic"])
    content.append(footer)

    # Build the PDF
    pdf.build(content)

    print("✅ PDF generated successfully!")

# Run the function
generate_pdf("my_report.pdf")
